version: "3.8"

services:
  mh-bot:
    build: .
    container_name: mh-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    restart: unless-stopped
    # Uncomment the line below if you want to use an existing image instead of building
    # image: mh-bot:latest
