export const huntingHorns = [
    {
        name: "Esperanza Horn",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A guild-crafted horn from the Esperanza line.",
        attack: 210,
        element: null,
        affinity: 0,
        echoBubble: "Evasion & Movement Speed Up",
        skills: ["Critical Eye Lv 2", "Speed Sharpening Lv 2"],
    },
    {
        name: "G. Rathalos Feroce",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Guardian Rathalos horn with a sharp fire tone.",
        attack: 210,
        element: "Fire 300",
        affinity: 15,
        echoBubble: "Stamina Regeneration",
        skills: ["Critical Element Lv 1", "Master's Touch Lv 1"],
    },
    {
        name: "Great Bagpipe",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A bagpipe-style horn forged from ore and bone.",
        attack: 210,
        element: null,
        affinity: 0,
        echoBubble: "Evasion & Movement Speed Up",
        skills: ["Critical Draw Lv 3", "Horn Maestro Lv 1"],
    },
    {
        name: "Precipice Kovira",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Jin Dahaad horn with a cold, crushing edge.",
        attack: 210,
        element: "Ice 500",
        affinity: 0,
        echoBubble: "Ailments/Blights Negated",
        skills: ["Slugger Lv 3"],
    },
    {
        name: "Kae-jin's Lament",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "An Xu Wu horn with a watery, mournful tone.",
        attack: 220,
        element: "Water 250",
        affinity: 0,
        echoBubble: "Stamina Regeneration",
        skills: ["Stamina Thief Lv 3", "Horn Maestro Lv 1"],
    },
    {
        name: "Ajara-Jivaka",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "An Ajarakan horn built for explosive impact.",
        attack: 210,
        element: "Blast 250",
        affinity: 10,
        echoBubble: "Evasion & Movement Speed Up",
        skills: ["Slugger Lv 3"],
    },
    {
        name: "Sandsea Ghantisil",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Balahara horn shaped by the desert sands.",
        attack: 210,
        element: "Water 300",
        affinity: 10,
        echoBubble: "Evasion & Movement Speed Up",
        skills: ["Slugger Lv 3"],
    },
    {
        name: "Perun Clairhorn",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Rey Dau horn charged with thunder.",
        attack: 220,
        element: "Thunder 300",
        affinity: 0,
        echoBubble: "Health Regeneration",
        skills: ["Stamina Thief Lv 3", "Horn Maestro Lv 1"],
    },
    {
        name: "Glass Royale",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A paralysis horn from the Vespoid line.",
        attack: 200,
        element: "Paralysis 400",
        affinity: 0,
        echoBubble: "Evasion & Movement Speed Up",
        skills: ["Protective Polish Lv 3", "Speed Sharpening Lv 2"],
    },
    {
        name: "Hardened Bone Horn",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A reinforced bone horn with no single monster tie.",
        attack: 220,
        element: null,
        affinity: 0,
        echoBubble: "Defense & Elemental Res Up",
        skills: ["Stamina Thief Lv 3", "Attack Boost Lv 1"],
    },
    {
        name: "Farsounder Honga",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Guardian Doshaguma horn with a heavy, grinding beat.",
        attack: 240,
        element: null,
        affinity: -5,
        echoBubble: "Stamina Regeneration",
        skills: ["Slugger Lv 2", "Horn Maestro Lv 1"],
    },
    {
        name: "G. Resounding Galahad",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Guardian Arkveld horn with a dragon-heavy tone.",
        attack: 230,
        element: "Dragon 250",
        affinity: -10,
        echoBubble: "Ailments/Blights Negated",
        skills: ["Horn Maestro Lv 2"],
    },
    {
        name: "Resounding Galahad",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "An Arkveld horn built for defense and elemental resistance.",
        attack: 210,
        element: "Dragon 400",
        affinity: 0,
        echoBubble: "Defense & Elemental Res Up",
        skills: ["Slugger Lv 2", "Horn Maestro Lv 2"],
    },
    {
        name: "Grudgesounder Urga",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Guardian Doshaguma horn that hits with grudging force.",
        attack: 250,
        element: null,
        affinity: -15,
        echoBubble: "Health Regeneration",
        skills: ["Stamina Thief Lv 3", "Horn Maestro Lv 1"],
    },
    {
        name: "War Conga",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Congalala horn that mixes brute force with swagger.",
        attack: 210,
        element: null,
        affinity: 5,
        echoBubble: "Attack & Affinity Up",
        skills: ["Horn Maestro Lv 2", "Speed Sharpening Lv 1"],
    },
    {
        name: "Kut-ku Cantabile",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Yian Kut-Ku horn with a fiery, bird-wyvern sound.",
        attack: 230,
        element: "Fire 500",
        affinity: 0,
        echoBubble: "Health Regeneration",
        skills: ["Stamina Thief Lv 3", "Horn Maestro Lv 1"],
    },
    {
        name: "Fulgurhowl Guardiana",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Guardian Fulgur Anjanath horn crackling with thunder.",
        attack: 210,
        element: "Thunder 400",
        affinity: 15,
        echoBubble: "Evasion & Movement Speed Up",
        skills: ["Critical Element Lv 3"],
    },
    {
        name: "Crazed Melody",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Gypceros horn that turns poison into a weird tune.",
        attack: 230,
        element: "Poison 400",
        affinity: 0,
        echoBubble: "Stamina Regeneration",
        skills: ["Critical Draw Lv 3", "Horn Maestro Lv 1"],
    },
    {
        name: "Queen Chordmaker",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Rathian horn with a poisonous royal edge.",
        attack: 200,
        element: "Poison 250",
        affinity: 15,
        echoBubble: "Health Regeneration",
        skills: ["Critical Status Lv 3", "Poison Duration Up Lv 1"],
    },
    {
        name: "Rathalos Feroce",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Rathalos horn that channels scorching fire.",
        attack: 200,
        element: "Fire 400",
        affinity: 10,
        echoBubble: "Evasion & Movement Speed Up",
        skills: ["Critical Boost Lv 3"],
    },
    {
        name: "Gramklang",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Gore Magala horn laced with dragon and frenzy power.",
        attack: 200,
        element: "Dragon 300",
        affinity: 20,
        echoBubble: "Evasion & Movement Speed Up",
        skills: ["Critical Element Lv 3"],
    },
    {
        name: "Blazing Gariel",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Zoh Shia horn wrapped in white flame.",
        attack: 220,
        element: "Dragon 250",
        affinity: 5,
        echoBubble: "Health Regeneration",
        skills: ["Whiteflame Torrent Lv 1"],
    },
    {
        name: "Summoning Bell",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Mizutsune horn with a smooth water melody.",
        attack: 210,
        element: "Water 350",
        affinity: 15,
        echoBubble: "Stamina Regeneration",
        skills: ["Slicked Blade Lv 3", "Critical Element Lv 1"],
    },
    {
        name: "Allysyl Muse",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Seregios horn with razor-sharp momentum.",
        attack: 210,
        element: null,
        affinity: -25,
        echoBubble: "Evasion & Movement Speed Up",
        skills: ["Bladescale Honing Lv 1"],
    },
    {
        name: "Lagia Thunderpeal",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Lagiacrus horn crackling with thunder.",
        attack: 210,
        element: "Thunder 450",
        affinity: 0,
        echoBubble: "Defense & Elemental Res Up",
        skills: ["Slugger Lv 2", "Convert Thunder Resistance Lv 1"],
    },
    {
        name: "Gogma Status",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Gogma horn focused on status pressure.",
        attack: null,
        element: null,
        affinity: null,
        echoBubble: null,
        skills: [],
    },
    {
        name: "Gogma Element",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Gogma horn focused on elemental pressure.",
        attack: null,
        element: null,
        affinity: null,
        echoBubble: null,
        skills: [],
    },
    {
        name: "Gogma Raw",
        customEmojiName: "hh",
        fallbackEmoji: "🎵",
        description: "A Gogma horn focused on raw damage.",
        attack: null,
        element: null,
        affinity: null,
        echoBubble: null,
        skills: [],
    },
];